server:
  port: 8090
  
spring:
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:h2:file:/home/gleissongtr/DESENV/DBGnote
    username: sa
    password:
    driverClassName: org.h2.Driver